### ISSUE TITLE
EPoll register

### ISSUE THREAD

**Issue by SatoshiR** [vibe-d/eventcore#10]
Hi,
in posix/epoll.d on line 72 you have 2 times EPOLLRDHUP
```
if (mask & EventMask.status) ev.events |= EPOLLERR|EPOLLRDHUP|EPOLLRDHUP;
```

shouldn't it be EPOLLRDHUP | EPOLLHUP ?

**Comment by s-ludwig** [comment]
Indeed, thanks for the notice! I'll commit a fix in a moment.
