### ISSUE TITLE
Compilation fails on FreeBSD 12.0

### ISSUE THREAD

**Issue by vans9** [vibe-d/eventcore#133]
Hi.
I have FreeBSD 12.0, ldc2 from packages and dmd2 from dlang.org.
I have created simple dub project with vibe.d in dependencies.

> $ dub build
> Running pre-generate commands for vibe-d:tls...
> Performing "debug" build using /usr/local/bin/ldc2 for x86_64.
> ...
> eventcore 0.8.48: building configuration "kqueue"...
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import idtype_t not found
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import WEXITED not found, did you mean function core.sys.posix.sys.wait.WIFEXITED?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import waitid not found, did you mean function core.sys.posix.sys.wait.waitpid?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/driver.d(58,41): Error: template instance `eventcore.drivers.posix.processes.PosixEventDriverProcesses!(SelectEventLoop)` error instantiating
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/select.d(26,27):        instantiated from here: PosixEventDriver!(SelectEventLoop)
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import idtype_t not found
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import WEXITED not found, did you mean function core.sys.posix.sys.wait.WIFEXITED?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module `core.sys.posix.sys.wait` import waitid not found, did you mean function core.sys.posix.sys.wait.waitpid?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/driver.d(58,41): Error: template instance `eventcore.drivers.posix.processes.PosixEventDriverProcesses!(KqueueEventLoop)` error instantiating
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/kqueue.d(32,27):        instantiated from here: PosixEventDriver!(KqueueEventLoop)
> /usr/local/bin/ldc2 failed with exit code 1.

Building with dmd2 produces the same:
> $ dub build --compiler=dmd
> Running pre-generate commands for vibe-d:tls...
> Performing "debug" build using dmd for x86_64.
> ...
> eventcore 0.8.48: building configuration "kqueue"...
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import idtype_t not found
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import WEXITED not found, did you mean function core.sys.posix.sys.wait.WIFEXITED?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import waitid not found, did you mean function core.sys.posix.sys.wait.waitpid?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/driver.d(58,41): Error: template instance eventcore.drivers.posix.processes.PosixEventDriverProcesses!(SelectEventLoop) error instantiating
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/select.d(26,27):        instantiated from here: PosixEventDriver!(SelectEventLoop)
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import idtype_t not found
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import WEXITED not found, did you mean function core.sys.posix.sys.wait.WIFEXITED?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/processes.d(316,10): Error: module core.sys.posix.sys.wait import waitid not found, did you mean function core.sys.posix.sys.wait.waitpid?
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/driver.d(58,41): Error: template instance eventcore.drivers.posix.processes.PosixEventDriverProcesses!(KqueueEventLoop) error instantiating
> /home/s/.dub/packages/eventcore-0.8.48/eventcore/source/eventcore/drivers/posix/kqueue.d(32,27):        instantiated from here: PosixEventDriver!(KqueueEventLoop)
> dmd failed with exit code 1.

If I add missing definitions to the wait.d everything compiles ok.
So should I report it here or should I report it the dlang team and maybe the port maintainer?

**Comment by sakhmatd** [comment]
I have ran into the same exact issue.

Real bummer, as many of my servers run FreeBSD and I am not able to make any Vibe.d projects to build for them.

Let me know if I can assist in any way, would love to see this fixed.

**Comment by Geod24** [comment]
> So should I report it here or should I report it the dlang team and maybe the port maintainer?

It is definitely a druntime issue, so I'll send an issue there.

**Comment by sakhmatd** [comment]
I have filed a problem report with druntime [here](https://issues.dlang.org/show_bug.cgi?id=20852).

Thanks for pointing me in the right direction!

**Comment by sakhmatd** [comment]
[My pull request](https://github.com/dlang/druntime/pull/3113) with the missing definitions has been merged into druntime, you can probably safely close this issue.

**Comment by Geod24** [comment]
@sakhmatd : Thanks for taking care of this! With the current release cycle, this will only be available from August, unfortunately. Did you test a simple Vibe.d app / vibe.d test suite ?

**Comment by sakhmatd** [comment]
It appears that I didn't test it enough, after running some tests from the Vibe.d suite, it looks like wait.d needs a few more definitions. I've opened [another PR](https://github.com/dlang/druntime/pull/3115) to fix that.

With all the definitions from FreeBSD's sys/wait.h in place, the Vibe.d tests pass just fine. I ran some tests on a few projects of mine too.

**Comment by Geod24** [comment]
Thanks! I know from experience how easily those things slips through... Closing now.
