### ISSUE TITLE
code duplication within version block below.

### ISSUE THREAD

**Issue by ArjanKn** [vibe-d/eventcore#160]
https://github.com/vibe-d/eventcore/blob/5cb6ff7dd33def973740cc5cbf14a3c3bd31c028/source/eventcore/drivers/posix/sockets.d#L230

https://github.com/vibe-d/eventcore/blob/5cb6ff7dd33def973740cc5cbf14a3c3bd31c028/source/eventcore/drivers/posix/sockets.d#L237

**Comment by drug007** [comment]
Could you elaborate that? SO_REUSEADDRR and SO_REUSEPORT are different options

**Comment by ArjanKn** [comment]
I see.. Probably I did not red the code carefully enough back then.
