### ISSUE TITLE
Failed to run benchmark test on windows 10

### ISSUE THREAD

**Issue by Heromyth** [vibe-d/eventcore#51]
The http-server has no respond when running the benchmark  command at second.
In fact, you can't open the link http://127.0.0.1:8080/ from different browers.
Everything seems ok on linux.

OS: windows 10 x64
Compiler: dmd v2.078.3

Build command: 
1) dub build --config=winapi-optlink --arch=x86 --build=debug --compiler=dmd
2) dub build --config=winapi --arch=x86_64 --build=debug --compiler=dmd

Test code: examples/http-server.d (changed to listen on 0.0.0.0:8080)

Benchmark  tool: ApacheBench
ab -n 2 -c 1 -k -v 5  http://127.0.0.1:8080/

**Comment by Majestio** [comment]
120.0.0.1 or 127.0.0.1?

**Comment by Heromyth** [comment]
Maybe.
