### ISSUE TITLE
Overwriting notification callback.

### ISSUE THREAD

**Issue by anton-dutov** [vibe-d/eventcore#7]
Ref

    auto sockFd = eventDriver.sockets.connectStream(addr, null, (fd,  status) @safe nothrow {
        if (fd != StreamSocketFD.invalid) eventDriver.sockets.addRef(fd);
        //_isAttached = status == ConnectStatus.connected;
        if (fd != StreamSocketFD.invalid) eventDriver.sockets.releaseRef(fd);
    });

    eventDriver.sockets.addRef(sockFd);

    eventDriver.sockets.write(sockFd, msg.pack, IOMode.all, (fd, status, nbytes) @safe nothrow {
        // ...
    });

Exception:

    core.exception.AssertError@../../../.dub/packages/eventcore-0.8.3/eventcore/source/eventcore/drivers/posix/driver.d(241): Overwriting notification callback.
    ----------------
    ??:? nothrow @nogc @safe void eventcore.drivers.posix.driver.PosixEventLoop.setNotifyCallback!(1).setNotifyCallback(eventcore.driver.Handle!("fd", ulong, -1uL).Handle, nothrow @safe void delegate(eventcore.driver.Handle!("fd", ulong, -1uL).Handle)) [0xed733506]

**Comment by s-ludwig** [comment]
The error message should be changed to be higher level, but the issue here is that the write happens while the connection is still in progress. To be correct, the call to `write` needs to happen within the callback that is passed to `connectStream`.
