### ISSUE TITLE
Waiter count starts at non-zero?

### ISSUE THREAD

**Issue by Calrama** [vibe-d/eventcore#8]
Hi, I was interested in taking this out for a spin, but that the following code outputs `5` and then waits in the event loop seems strange:

```D
#! /usr/bin/env dub
/++ dub.sdl:
        name "waiter-count-non-zero"
        description "Waitercount non-zero"
        dependency "eventcore" version="~>0.8"
+/
module waiter_count_non_zero;

void main()
{
        print("%s", eventDriver.core.waiterCount);
        while (eventDriver.core.waiterCount)
                eventDriver.core.processEvents(Duration.max);
}

import eventcore.core : eventDriver;
import eventcore.internal.utils : print;
import core.time : Duration;
```

I would expect `waiterCount` to be `0`, seeing as I have not registered anything with the event loop, and the program to terminate (the event loop should not block if I have no handles/requests with it.

(This happens on Linux with version 0.8.8)

**Comment by s-ludwig** [comment]
Proper tests need to be added for this. Currently some internal events are created to implement certain features on certain platforms and it seems like the waiter count doesn't ignore those appropriately.
